
all: 
	@$(MAKE) -C pcie_a53_rw
	@$(MAKE) -C pcie_a53_rw install
	@$(MAKE) -C pcie_reg_rw
	@$(MAKE) -C pcie_reg_rw install
	@$(MAKE) -C xdma_v4l2_rw
	@$(MAKE) -C xdma_v4l2_rw install
	 

clean:
	@$(MAKE) -C pcie_a53_rw  clean
	@$(MAKE) -C pcie_reg_rw clean
	@$(MAKE) -C xdma_v4l2_rw clean

